---
rootless_docker_docker_url: "https://download.docker.com/linux/static/{{ rootless_docker_channel }}/{{ ansible_architecture }}/docker-{{ rootless_docker_version }}.tgz"
rootless_docker_rootless_url: "https://download.docker.com/linux/static/{{ rootless_docker_channel }}/{{ ansible_architecture }}/docker-rootless-extras-{{ rootless_docker_version }}.tgz"
